#joriel fairbanks
#10/1/2026
m = int(input("what is m"))
#m is the amount of numbers in the fibonacci sequence that will be printed out
fib = [0,1]
#the list starts at 0 and 1 because those are the first two numbers in the fibonacci sequence
i = 2 
#i is the spot in the list where the next number will be inserted
while i < m: 
    #above is the loop that will keep going until the amount of numbers in the fibonacci sequence is equal to m
    #this is how m is the number of numbers in the fibonacci sequence that will be printed out
    fib.insert(i, fib[i-1] + fib[i-2])
    #this line is the formula for the fibonacci sequence, it takes the last two numbers in the list and adds them together to get the next number in the sequence
    #the i-1 and i-2 are the last two numbers in the list, and the i is the spot in the list where the next number will be inserted
    i += 1
    #have to add 1 to i so that the next number will be inserted in the next spot in the list
for k in fib:
    #this loop will print out all the numbers in the fibonacci sequence that were generated by the while loop
    print(k, end=" ")
    #its really more just to be neat and pretty, it will print all the numbers in the fibonacci sequence on one line with a space in between each number

#below is the same code as above but it is commented out and it is a different way to do the same thing, it uses a for loop instead of a while loop
#fib2 = [0,1]
#for j in range(2,m):
#    fib2.insert(j, fib2[j-1] + fib2[j-2])
#print('The first fibonacci number is ', fib2[0])
#print('The second fibonacci number is ', fib2[1])
#print('The third fibonacci number is ', fib2[2])
#print('The fourth fibonacci number is ', fib2[3])
#print('The fifth fibonacci number is ', fib2[4])
#above might be able to be compressed into a smaller amount of code (faster??)

